apiVersion: batch/v1
kind: Job
metadata:
  name: cyclonus
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - command:
            - ./cyclonus
            - generate
            - --noisy=true
            - --ignore-loopback=true
            - --cleanup-namespaces=true
            - --perturbation-wait-seconds=5
            - --pod-creation-timeout-seconds=30
            - --job-timeout-seconds=2
            - --server-protocol=TCP,UDP
            - --verbosity=trace
            #- --include=direction, end-port, ingress, egress, numbered-port, port, protocol, tcp, udp
          name: cyclonus
          imagePullPolicy: Never
          image: acnpublic.azurecr.io/azure-npm:cyclonous-endport
          #image: mfenwick100/cyclonus:latest
      serviceAccount: cyclonus