name: Cyclonus Network Policy Test

on:
  workflow_dispatch:
  push:
    branches:
      -  enable-endport
  pull_request:
    paths:
      - 'npm/**'
  schedule:
    # run once a day at midnight
    - cron: '0 0 * * *'

jobs:
  cyclonus-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make cyclonous image
        run: |
          git checkout -b enable-endport
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./cmd/cyclonus/cyclonus ./cmd/cyclonus
          docker build -t acnpublic.azurecr.io/azure-npm:cyclonous-endport ./cmd/cyclonus

      - name: Setup Kind
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
          config: ./hack/kind/azure-npm/kind.yaml
          name: npm-kind
      
      - name: Install Azure NPM
        run: |
          sed -i 's/mcr.microsoft.com\/containernetworking\/azure-npm:v1.4.1/acnpublic.azurecr.io\/azure-npm:endport/' ./hack/kind/azure-npm/azure-npm.yaml
          kind load docker-image acnpublic.azurecr.io/azure-npm:endport --name npm-kind
          kind load docker-image acnpublic.azurecr.io/azure-npm:cyclonous-endport --name npm-kind
          docker pull k8s.gcr.io/e2e-test-images/agnhost:2.28
          kind load docker-image k8s.gcr.io/e2e-test-images/agnhost:2.28 --name npm-kind
          kubectl apply -f ./hack/kind/azure-npm/azure-npm.yaml

      - name: Run Cyclonus network policy test
        run: bash ./hack/kind/test-cyclonus-with-azure-npm.sh

      - name: Fetch logs
        if: always()
        run: |
          kubectl logs -n kube-system -l k8s-app=azure-npm --tail -1 --prefix > npm-logs.txt
          mv ./hack/kind/cyclonus-test.txt ./cyclonus-test.txt

      - name: 'Upload Logs'
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: logs
          path: |
            ./npm-logs.txt
            ./cyclonus-test.txt

